### ISSUE TITLE
module gconftool-2 fails with late ansible

### ISSUE THREAD

**Issue by stefangweichinger** [JBKahn/provisioning-local#17]
not urgent or important, just want to provide feedback ->

When I run my forked copy of your provisioning-local repo with a recent checkout of ansible (I am currently on ansible 2.1.0.0 (detached HEAD b599477242), a task using gconftool-2 fails with:

> TASK [common : install fonts - set system font] ********************************
task path: /home/sgw/provisioning-local/roles/common/tasks/font.yml:84
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: sgw
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1465389604.39-33377802444044 `" && echo ansible-tmp-1465389604.39-33377802444044="` echo $HOME/.ansible/tmp/ansible-tmp-1465389604.39-33377802444044 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp3CQy_s TO /home/sgw/.ansible/tmp/ansible-tmp-1465389604.39-33377802444044/gconftool-2
<127.0.0.1> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python2.7 /home/sgw/.ansible/tmp/ansible-tmp-1465389604.39-33377802444044/gconftool-2; rm -rf "/home/sgw/.ansible/tmp/ansible-tmp-1465389604.39-33377802444044/" > /dev/null 2>&1 && sleep 0'
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "gconftool-2"}, "module_stderr": "  File \"/home/sgw/.ansible/tmp/ansible-tmp-1465389604.39-33377802444044/gconftool-2\", line 88\n    from ansible_module_gconftool-2 import main\n                                 ^\nSyntaxError: invalid syntax\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

Same task runs fine with older versions of ansible. Could you have a look?

In general: thanks a lot for that repo, I modified it for my own usage and use it regularly.

**Comment by JBKahn** [comment]
No problem, glad someone else has used it. Haven't needed to run it in a few months so it's out of date with current ansible.  Does it run fine on the version just before that one?

**Comment by stefangweichinger** [comment]
works with tags/v2.0.2.0-1 -> ansible 2.0.2.0 (detached HEAD 24d9e5e0b4)
fails with tags/v2.1.0.0-1 -> ansible 2.1.0.0 (detached HEAD b599477242)

**Comment by JBKahn** [comment]
Alright, I'll take a look this weekend.

**Comment by stefangweichinger** [comment]
this might be the same issue: [http://stackoverflow.com/questions/37514125/syntax-error-in-ansible-regardless-of-input-when-using-ec2-module](url)

Although we have "ansible_python_interpreter=/usr/bin/python2" in HOSTS

**Comment by JBKahn** [comment]
oh, based on that I assume it might be executing it in python 3? I'll double check it's python 2/3 compatible and fix it if it's not and see if that solves it? I'll fiddle around this weekend.

**Comment by stefangweichinger** [comment]
running it with -vvvv mentions python2.7

# for 2.1
<127.0.0.1> EXEC /bin/sh -c 'LANG=de_AT.UTF-8 LC_ALL=de_AT.UTF-8 LC_MESSAGES=de_AT.UTF-8 /usr/bin/python2.7 /home/sgw/.ansible/tmp/ansible-tmp-1465497915.96-131643139944645/gconftool-2; rm -rf "/home/sgw/.ansible/tmp/ansible-tmp-1465497915.96-131643139944645/" > /dev/null 2>&1 && sleep 0'

# for 2.0.2 it is nearly identical
127.0.0.1 EXEC /bin/sh -c 'LANG=de_AT.UTF-8 LC_ALL=de_AT.UTF-8 LC_MESSAGES=de_AT.UTF-8 /usr/bin/python2.7 /home/sgw/.ansible/tmp/ansible-tmp-1465499348.76-213076821153402/gconftool-2; rm -rf "/home/sgw/.ansible/tmp/ansible-tmp-1465499348.76-213076821153402/" > /dev/null 2>&1'

I am no programmer so this is just simple comparing ... trying to figure it out ;-)
again, no hurries.

**Comment by JBKahn** [comment]
Ohhhh got it. They changes the way they import modules and so now it uses an actual import statement which breaks because it's `gconftool-2`. If you rename all cases of `gconftool-2` in the script ot `gconftool2` and rename the file in the ansible_modules folder from `gconftool-2` to `gconftool2` it should work. Let me know if that solves it.

**Comment by JBKahn** [comment]
like this: https://github.com/JBKahn/provisioning-local/pull/18

**Comment by stefangweichinger** [comment]
yes, that fixes it. Thanks!
